app:
  namespace: ""
  secret_name: ""
  aws_secret_name: ""
  account: ""
  stack_name: ""
  database_secret_names_to_use:
  pod:
    min:
    max:
    port:
    healthCheckPath:
    initialHealthCheckDelay:
  autoscaling:
    cpu:
      enabled: false
      metricType: Utilization
      value: "50"
    memory:
      enabled: false
      metricType: Utilization
      value: "50"
  service:
    formatted_dns_names: ""
    observability:
      enabled:
      endpoint: ""
    name:
    protocol: TCP
    port:
  resources:
    requests:
      memory: "256Mi"
      cpu: "125m"
    limits:
      memory: "256Mi"
      cpu: "125m"

image:
  name:
  tag:
  url: