apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${secret_name}
  namespace: ${secret_namespace}
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: ${secret_name}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ${secret_key}