apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.app.secret_name }}
  namespace: {{ .Values.app.namespace }}
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: secretstore
    kind: ClusterSecretStore
  target:
    name: {{ .Values.app.secret_name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.app.aws_secret_name }}