apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.app.service.name }}
  namespace: {{ .Release.namespace }}
  labels:
    traffic-type: external
spec:
  entryPoints:
    - web
  routes:
    - match: {{ .Values.app.service.formatted_dns_names }}
      kind: Rule
      services:
        - name: {{ .Values.app.service.name }}
          port: {{ .Values.app.pods.port }}